import './globals.css'
import { Inter, sentie } from 'next/font/google'
import localFonts from 'next/font/local'
import Navbar from './components/global/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Federal civil service club',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://api.fontshare.com/v2/css?f[]=sentient@1&display=swap" rel="stylesheet"/>
      </head>
      <body >
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
